# Based on the app_type value, uncomment the following statements.
app_type: custom

# Drupal

# Settings for when installing fresh.
#drupal_build_composer: false
#drupal_build_composer_project: true
#drupal_install_profile: resilient

# Installing from existing configuration
#drupal_site_exists: false
#drupal_build_composer: true
#drupal_build_composer_project: false
#drupal_composer_path: false
#drupal_install_profile: 'config_installer'
#drupal_site_install_extra_args: [ "config_installer_sync_configure_form.sync_directory=../config/sync" ]
