---
- src: geerlingguy.repo-remi
- src: geerlingguy.firewall
- src: geerlingguy.git
- src: geerlingguy.postfix
- src: geerlingguy.apache
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.nginx
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.php-pecl
- src: geerlingguy.composer
- src: geerlingguy.mysql
- src: geerlingguy.php-mysql
- src: geerlingguy.postgresql
- src: geerlingguy.php-pgsql
- src: geerlingguy.drupal-console
- src: geerlingguy.drush
- src: geerlingguy.memcached
- src: geerlingguy.php-memcached
- src: geerlingguy.php-tideways
- src: geerlingguy.php-xdebug
- src: geerlingguy.php-xhprof
- src: thom8.php-upload-progress
- src: geerlingguy.blackfire
- src: geerlingguy.adminer
- src: geerlingguy.pimpmylog
- src: geerlingguy.daemonize
- src: geerlingguy.mailhog
- src: franklinkim.newrelic
- src: geerlingguy.nodejs
- src: geerlingguy.redis
- src: geerlingguy.php-redis
- src: geerlingguy.ruby
- src: geerlingguy.java
- src: arknoll.selenium
- src: geerlingguy.solr
- src: geerlingguy.elasticsearch
- src: geerlingguy.varnish
- src: geerlingguy.drupal
- src: geerlingguy.security
- src: lammensj.wordpress